#ifndef EXAMPLE_GAME_OF_LIFE_SOA_CONFIGURATION_H
#define EXAMPLE_GAME_OF_LIFE_SOA_CONFIGURATION_H

#define OPTION_DRAW true
#define SIZE_X 200
#define SIZE_Y 100

#endif  // EXAMPLE_GAME_OF_LIFE_SOA_CONFIGURATION_H
