#ifndef EXAMPLE_GAME_OF_LIFE_SOA_CONFIGURATION_H
#define EXAMPLE_GAME_OF_LIFE_SOA_CONFIGURATION_H

#define OPTION_DRAW false
#define SIZE_X 1000
#define SIZE_Y 500

#endif  // EXAMPLE_GAME_OF_LIFE_SOA_CONFIGURATION_H
