#ifndef EXAMPLE_DEFRAG_BENCH_CONFIGURATION_H
#define EXAMPLE_DEFRAG_BENCH_CONFIGURATION_H

static const int kSize = 32768*2048;
static const int kRetainFactor = 4;

#endif  // EXAMPLE_DEFRAG_BENCH_CONFIGURATION_H
