#ifndef EXAMPLE_CONFIGURATION_DYNASOAR_ALLOCATOR_CONFIG_H
#define EXAMPLE_CONFIGURATION_DYNASOAR_ALLOCATOR_CONFIG_H

#ifdef CHK_ALLOCATOR_DEFINED
#error Allocator already defined
#else
#define CHK_ALLOCATOR_DEFINED
#endif  // CHK_ALLOCATOR_DEFINED

#include "dynasoar.h"

#endif  // EXAMPLE_CONFIGURATION_DYNASOAR_ALLOCATOR_CONFIG_H
